# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6150f8a368f785f72991e0bf61653173dd5aacd9189badb90ec0305ccf879815abafb99424e9fd9f036f773091c1b3ed5a04776234377eb2ff457e9e6c2cee47

test:
  secret_key_base: e1b8fd3de29ddc8c13c2bf585ee360375a54f6864ec89df16c9cce08cd94b3287d2997041cc1d684fa938c1fa444d69634dbe76e0c2d327c1a71c6a743f1dbf0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
